spring.application.name=Omegamon

telegram.token=${telegram.token}
latitude=${latitude}
longitude=${longitude}

weather_url=${weather_url}
weather.token=${weather.token}

price_url=${price_url}

news_url=${news_url}
news.token=${news.token}